int_fillval: &int_fillval -9223372036854775808
min_epoch: &min_epoch -315575942816000000
max_epoch: &max_epoch 3155630469184000000
max_uint16: &max_uint16 65535

data_min: &data_min 0
data_max: &data_max 4096

sample_rate_min: &sample_rate_min -130
sample_rate_max: &sample_rate_max 130

int_maxval: &int_maxval 9223372036854775807

l1b_data_base: &l1b_data_base
  VALIDMIN: *data_min
  VALIDMAX: *data_max
  DISPLAY_TYPE: spectrogram
  DEPEND_0: epoch
  FORMAT: I12
  UNITS: dN
  VAR_TYPE: data
  # VAR_PURPOSE: PRIMARY
  CATDESC: ""
  FIELDNAM: ""
  FILLVAL: *int_fillval
  LABLAXIS: ""

l1b_tof_base: &l1b_tof_base
  <<: *l1b_data_base
  DEPEND_1: time_high_sr

l1b_target_base: &l1b_target_base
  <<: *l1b_data_base
  DEPEND_1: time_low_sr

sample_rate_base: &sample_rate_base
  DISPLAY_TYPE: no_plot
  CATDESC: ""
  FIELDNAM: ""
  FILLVAL: -1.0e+31
  VALIDMIN: *sample_rate_min
  VALIDMAX: *sample_rate_max
  DEPEND_0: epoch
  FORMAT: F64.5
  LABLAXIS: Time
  UNITS: microseconds
  VAR_TYPE: support_data # Not in attrs file
  VAR_NOTES:  The number of microseconds since the event.
              0 is the start of data collection, negative
              numbers represent data collected prior to a dust event

trigger_base: &trigger_base
  VALIDMIN: 0
  VALIDMAX: *int_maxval
  DISPLAY_0: epoch
  DISPLAY_TYPE: no_plot
  CATDESC: ""
  FIELDNAM: ""
  VAR_TYPE: support_data
  FILLVAL: *int_fillval
  LABLAXIS: ""
  FORMAT: I12
  UNITS: ""

low_sr_attrs:
  <<:  *sample_rate_base
  CATDESC: Low sample rate time steps for a dust event.
  FIELDNAM: Low Sample Rate Time
  VAR_NOTES: The low sample rate in microseconds. Steps are approximately 1/4.025
             microseconds in duration. Used by the Ion_Grid, Target_Low, and
             Target_High variables.

high_sr_attrs:
  <<:  *sample_rate_base
  CATDESC: High sample rate time steps for a dust event.
  FIELDNAM: High Sample Rate Time
  VAR_NOTES: The high sample rate in microseconds. Steps are approximately 1/260
    microseconds in duration. Used by the TOF_High, TOF_Mid, and
    TOF_Low variables.

tof_high_attrs:
  <<: *l1b_tof_base
  CATDESC: Time of flight waveform on the high-gain channel
  FIELDNAM: High Gain Time of Flight
  LABLAXIS: TOF High Ampl.
  VAR_NOTES: High gain channel of the time-of-flight signal.
        Sampled at 260 Megasamples per second, with a 10-bit resolution.
        Data is used to quantify dust composition.

tof_mid_attrs:
  <<: *l1b_tof_base
  CATDESC: Time of flight waveform on the mid-gain channel
  FIELDNAM: Mid Gain Time of Flight
  LABLAXIS: TOF Mid Ampl.
  VAR_NOTES: Mid gain channel of the time-of-flight signal.
        Sampled at 260 Megasamples per second, with a 10-bit resolution.
        Data is used to quantify dust composition.

tof_low_attrs:
  <<: *l1b_tof_base
  FILLVAL: *int_fillval
  CATDESC: Time of flight waveform on the low-gain channel
  FIELDNAM: Low Gain Time of Flight
  LABLAXIS: TOF Low Ampl.
  VAR_NOTES: Low gain channel of the time-of-flight signal.
        Sampled at 260 Megasamples per second, with a 10-bit resolution.
        Data is used to quantify dust composition.


target_low_attrs:
  <<: *l1b_target_base
  CATDESC: Target low charge sensitive amplifier waveform
  FIELDNAM: Low Target Signal
  LABLAXIS: Low Target Ampl.
  VAR_NOTES: Low gain channel of IDEX's target signal.
        Sampled at 3.75 Msps with 12-bit resolution.
        Data is used to quantify dust charge.

target_high_attrs:
  <<: *l1b_target_base
  CATDESC: Ion grid charge sensitive amplifier waveform
  FIELDNAM: High Target Signal
  LABLAXIS: High Target Ampl.
  VAR_NOTES: High gain channel of IDEX's target signal.
        Sampled at 3.75 Msps with 12-bit resolution.
        Data is used to quantify dust charge.

ion_grid_attrs:
  <<: *l1b_target_base
  CATDESC: Ion grid charge sensitive amplifier waveform data
  FIELDNAM: Ion Grid Signal
  LABLAXIS: Ion Grid Ampl.
  VAR_NOTES: This is the ion grid signal from IDEX.
        Sampled at 3.75 Msps with 12-bit resolution.
        Data is used to quantify dust charge.

shcoarse:
  <<: *trigger_base
  CATDESC: Time of packet generation (not data acquisition), as integer seconds since epoch
  FIELDNAM: Secondary header coarse time
  LABLAXIS: Packet Generation Time (Coarse)
  UNITS: seconds

shfine:
  <<: *trigger_base
  CATDESC: Time of packet generation, each DN represents 20usec within current second
  FIELDNAM: Secondary header fine time
  VALIDMAX: *max_uint16
  LABLAXIS: Packet Generation Time (Fine)
  UNITS: seconds

detector_voltage:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Detector Voltage
  CATDESC: Last measurement in raw dN for processor board signal - "Detector Voltage"
  LABLAXIS: Voltage
  UNITS: V

sensor_voltage:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Sensor Voltage
  CATDESC: Last measurement in raw dN for processor board signal - "Sensor Voltage"
  LABLAXIS: Voltage
  UNITS: V

target_voltage:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Target Voltage
  CATDESC: Last measurement in raw dN for processor board signal - "Target Voltage"
  LABLAXIS: Voltage
  UNITS: V

reflectron_voltage:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Reflectron Voltage
  CATDESC: Last measurement in raw dN for processor board signal - "Reflectron Voltage"
  LABLAXIS: Voltage
  UNITS: V

rejection_voltage:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Rejection Voltage
  CATDESC: Last measurement in raw dN for processor board signal - "Rejection Voltage"
  LABLAXIS: Voltage
  UNITS: V

current_hvps_sensor:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Detector Current
  CATDESC: Last measurement in raw dN for processor board signal - "Detector Current "
  LABLAXIS: Current
  UNITS: mA

current_1v_pol:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: 1V POL Current
  CATDESC: Last measurement in raw DN for Processor Board signal - "1V POL Current"
  LABLAXIS: Current
  UNITS: mA

current_1p9v_pol:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: 1.9V POL Current
  CATDESC: Last measurement in raw DN for Processor Board signal - "1.9V POL Current"
  LABLAXIS: Current
  UNITS: mA

temperature_1:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: ProcBd Temp1
  CATDESC: Last measurement in raw DN for Processor Board signal - "ProcBd Temp1"
  LABLAXIS: Temperature
  UNITS: C

temperature_2:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: ProcBd Temp2
  CATDESC: Last measurement in raw DN for Processor Board signal - "ProcBd Temp2"
  LABLAXIS: Temperature
  UNITS: C

voltage_1v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: 1V Voltage
  CATDESC: Last measurement in raw DN for Processor Board signal - "1V Voltage"
  LABLAXIS: Voltage
  UNITS: V

fpga_temperature:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: FPGA Temp
  CATDESC: Last measurement in raw DN for Processor Board signal - "FPGA Temp"
  LABLAXIS: Temperature
  UNITS: C

voltage_1p9v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: 1.9V Voltage
  CATDESC: Last measurement in raw DN for Processor Board signal - "1.9V Voltage"
  LABLAXIS: Voltage
  UNITS: V

voltage_3p3v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: 3.3V Voltage
  CATDESC: Last measurement in raw DN for Processor Board signal - "3.3V Voltage"
  LABLAXIS: Voltage
  UNITS: V

positive_current_hvps:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Sensor IP
  CATDESC: Last measurement in raw DN for HVPS Board signal - "Sensor IP"
  LABLAXIS: Current
  UNITS: mA

negative_current_hvps:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: Sensor IN
  CATDESC: Last measurement in raw DN for HVPS Board signal - "Sensor IN"
  LABLAXIS: Current
  UNITS: mA

voltage_3p3_ref:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P3.3VREF_HK
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P3.3VREF_HK"
  LABLAXIS: Voltage
  UNITS: V

voltage_3p3_op_ref:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P3.3VREF_OP
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P3.3VREF_OP"
  LABLAXIS: Voltage
  UNITS: V

voltage_neg6v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: N6V
  CATDESC: Last measurement in raw DN for LVPS Board signal - "N6V"
  LABLAXIS: Voltage
  UNITS: V

voltage_pos6v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P6V
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P6V"
  LABLAXIS: Voltage
  UNITS: V

voltage_pos16v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P16V
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P16V"
  LABLAXIS: Voltage
  UNITS: V

voltage_pos3p3v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P3.3V
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P3.3V"
  LABLAXIS: Voltage
  UNITS: V

voltage_neg5v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: N5V
  CATDESC: Last measurement in raw DN for LVPS Board signal - "N5V"
  LABLAXIS: Voltage
  UNITS: V

voltage_pos5v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P5V
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P5V"
  LABLAXIS: Voltage
  UNITS: V

current_3p3_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P3.3_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P3.3_IMON"
  LABLAXIS: Current
  UNITS: A

current_16v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P16V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P16V_IMON"
  LABLAXIS: Current
  UNITS: A

current_6v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P6V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P6V_IMON"
  LABLAXIS: Current
  UNITS: A

current_neg6v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: N6V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "N6V_IMON"
  LABLAXIS: Current
  UNITS: A

current_5v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P5V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P5V_IMON"
  LABLAXIS: Current
  UNITS: A

current_neg5v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: N5V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "N5V_IMON"
  LABLAXIS: Current
  UNITS: A

current_2p5v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: P2.5V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "P2.5V_IMON"
  LABLAXIS: Current
  UNITS: A

current_neg2p5v_bus:
  <<: *trigger_base
  VALIDMAX: 4095
  FIELDNAM: N2.5V_IMON
  CATDESC: Last measurement in raw DN for LVPS Board signal - "N2.5V_IMON"
  LABLAXIS: Current
  UNITS: A
